block_size=256
CUDA_VISIBLE_DIVICES=1 python compress_bd3lm_optim.py \
    algo.backbone=dit \
    algo.T=10 \
    block_size=${block_size} \
    loader.eval_batch_size=10 \
    sampling.checkpoint_path=/data_133/rtq/BD3LM-SSCC/outputs/train/2026.02.01/001609/checkpoints/best.ckpt \
    sampling.first_hitting=False \
    sampling.reset_channel_context=True \
    model.length=1024 \
    data.test_dataset=CIFAR10 \
    data.image_size_test=32 \
    data.num_images_test=10 \
    model.attn_backend=sdpa \